name: "Github Actions Workflow Demo"
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonning Code to Ubuntu
        uses: actions/checkout@v3

      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Dependencies Installation
        run: pip3 install -r requirements.txt

      - name: Execution of Unit Testing
        run: pytest test.py
